name: Build and Upload Artifacts

on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.21.3]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build binary
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          GOOS=linux
        elif [ "${{ matrix.os }}" = "windows-latest" ]; then
          GOOS=windows
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          GOOS=darwin
        fi
        GOARCH=amd64 go build -o telebotspam-${{ matrix.os }}-amd64 main.go
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: telebotspam-${{ matrix.os }}-amd64
        path: telebotspam-${{ matrix.os }}-amd64